version: '3.9'

services:
  mongo_service:
    container_name: mongo_container
    image: mongo:7.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
