version: '3.9'

services:
  auth_service:
    container_name: auth_container
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - mongo_service

  mongo_service:
    container_name: mongo_container
    image: mongo:7.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
