package mongo_store

import (
	"context"
	"test-task-auth-service-api/internal/models"

	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type MongoStore struct {
	db *mongo.Database
}

type RefreshTokenEntity struct {
	Id     primitive.ObjectID `bson:"_id,omitempty"`
	UserId string             `bson:"userId"`
	Value  string             `bson:"value"`
}

func New(db *mongo.Database) *MongoStore {
	return &MongoStore{db}
}

func createRefreshTokenEntity(refreshToken *models.RefreshToken) *RefreshTokenEntity {
	return &RefreshTokenEntity{
		// ID will be generated by MongoDB
		UserId: refreshToken.UserId,
		Value:  refreshToken.Value,
	}
}

func (s *MongoStore) SaveRefreshToken(ctx context.Context, refreshToken *models.RefreshToken) error {
	refreshTokenEntity := createRefreshTokenEntity(refreshToken)

	res, err := s.db.Collection("refresh_tokens").InsertOne(ctx, refreshTokenEntity)
	if err != nil {
		return err
	}

	// set ID from MongoDB
	refreshToken.Id = res.InsertedID.(primitive.ObjectID).Hex()

	return nil
}
